# Generated by Django 6.0.4 on 2026-04-26 07:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('venue_name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('seating_type', models.CharField(choices=[('reserved', 'Reserved Seating'), ('free', 'Free Seating')], default='free', max_length=20)),
            ],
            options={
                'ordering': ['venue_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=200)),
                ('event_datetime', models.DateTimeField()),
                ('artists', models.TextField(blank=True, help_text='Pisahkan nama artis dengan koma')),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.venue')),
            ],
            options={
                'ordering': ['event_datetime'],
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quota', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_categories', to='events.event')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
