# Generated by Django 5.2.6 on 2026-04-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
