# Generated by Django 5.2.6 on 2026-04-30 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='event',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='TicketCategory',
        ),
    ]
